config/routes.rb
Rails.application.routes.draw do

  post "users/create" => "users#create"
  post "users" => "users#account_update"
  get "users/account" => "users#account"
  get "users/edit" => "users#edit"
  post "users/update" => "users#profile_update"
  get "users/profile" => "users#profile"
  get "signup" => "users#new"
  post "login" => "users#login"
  delete "logout" => "users#logout"
  get "login" => "users#login_form"
  
  get "reservations" => "reservations#index"
  get "reservations/new" => "reservations#new"
  post "reservations/create" => "reservations#create"
  get "reservations/:id" => "reservations#show"
  
  get "rooms/new" => "rooms#new"
  post "rooms/create" => "rooms#create"
  get "rooms/search" => "rooms#search"
  get "rooms/posts" => "rooms#posts"
  get "rooms/:id" => "rooms#show"

  get "/" => "home#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :room

    def reservation_count
        (self.end - self.start).to_i
    end

    def total_amount
        room = Room.find(room_id)
        reservation_count * room.price
    end
end

app/models/room.rb
class Room < ApplicationRecord
    validates :name, {presence: true}
    validates :description, {presence: true}
    validates :price, {presence: true}
    validates :address, {presence: true}
    validates :thumbnail, {presence: true}

    def reservations
        return Reservation.where(user_id: self.id)
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    attr_accessor :check_account,
                  :check_profile

    def reservations
        Reservation.where(user_id: self.id)
    end

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, {uniqueness: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }, if: :check_account}
    validates :name, {presence: true}
    validates :icon, {presence: true, if: :check_profile}
    validates :introduce, {presence: true, if: :check_profile}
    validates :password, {presence: true, length: {minimum: 6}, if: :check_account}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    protect_from_forgery

    def set_current_user
        @current_user = User.find_by(id: session[:user_id])
    end

    def authenticate_user
        if @current_user == nil
            flash.now[:notice] = "ログインが必要です"
            redirect_to("/login")
        end
    end

    def forbid_login_user
        if @current_user
            flash.now[:notice] = "すでにログインしています"
            redirect_to("/")
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user, {only: [:index, :new, :create, :show]}
  

  def index
    @reservations = @current_user.reservations
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new(
      user_id: User.first.id,
      room_id: @room.id,
      start: params[:start_date],
      end: params[:end_date],
      person_count: params[:person_count]
    )
    @reservation_count = (@reservation.end - @reservation.start).to_i
    @total_price = @room.price * @reservation_count
  end

  def create
    reservation_param = params[:reservation]
    @reservation = Reservation.new(
      user_id: @current_user.id,
      room_id: reservation_param[:room_id],
      start: reservation_param[:start_date],
      end: reservation_param[:end_date],
      person_count: reservation_param[:person_count]
      )
      
    @reservation.save
    redirect_to "/reservations/#{@reservation.id}"
  end

  def show
    @reservation = Reservation.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user, {only: [:new, :create, :posts]}
  
  def index
    @rooms =Room.all
  end

  def new
    @room = Room.find_by(id: params[:id])
  end

  def create
    
    if params[:thumbnail].present?
      uploaded_file = params[:thumbnail]
      upload_path = File.join("uploads_room_images", uploaded_file.original_filename)
      File.open(Rails.root.join("public", upload_path), 'w+b') do |fp|
        fp.write  uploaded_file.read
      end
      thumbnail = File.join("/", upload_path)
    end

    @room = Room.new(
      name: params[:name],
      description: params[:description],
      price: params[:price],
      address: params[:address],
      thumbnail: thumbnail
      )
      if @room.save
        flash[:notice] = "ルームを登録しました"
        redirect_to("/rooms/#{@room.id}")
      else
        render("rooms/new")
      end
  end

  def show
    @room = Room.find(params[:id])
  end

  def search
    @rooms = Room.all

    if params[:area].present?
      @rooms = @rooms.where('address LIKE ?', "%#{params[:area]}%")
    end


    if params[:keyword].present?
      keyword = params[:keyword]
      @rooms = @rooms.where(['name LIKE ? OR description LIKE ?', "%#{keyword}%", "%#{keyword}%"])
    end

    @room_count = @rooms.count
  end
    
  def posts
    @rooms = Room.all.order(created_at: :desc)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:profile, :profile_update, :edit, :account, :account_update, :logout]}

  before_action :forbid_login_user, {only: [:new, :create, :login, :login_form]}

  def new
    @user = User.new
  end

  def create
    if params[:icon].present?
      uploaded_file = params[:icon]
      upload_path = File.join("uploads_user_icons", uploaded_file.original_filename)
      File.open(Rails.root.join("public", upload_path), 'w+b') do |fp|
        fp.write  uploaded_file.read
      end
      icon = File.join("/", upload_path)
    end

    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      check_account: true
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to("/users/profile")
    else
      render("users/new")
    end
  end

  def edit
  end

  def account
  end

  def account_update
    password = params[:password]
    password_confirmation = params[:password_confirmation]
    current_password = params[:current_password]

    if @current_user.authenticate(current_password)
      @current_user.email = params[:email]

      if password
        if password == password_confirmation
          @current_user.password = params[:password]
        else
          @current_user.errors.add("password_confirmation", " is incorrect")
          render("users/edit") and return
        end
      end

      if @current_user.save
        flash[:notice] = "Your account has been updated successfully."
        redirect_to("/") and return
      else
        render("users/edit")
      end
    else
      @current_user.errors.add("current password", " is incorrect")
      render("users/edit")
    end
  end

  def profile
  end

  def profile_update
    @current_user.check_profile = true

    if params[:user][:image].present?
      uploaded_file = params[:user][:image]
      upload_path = File.join("uploads_user_icons", uploaded_file.original_filename)
      File.open(Rails.root.join("public", upload_path), 'w+b') do |fp|
        fp.write  uploaded_file.read
      end
      icon = File.join("/", upload_path)
      @current_user.icon = icon
      @current_user.name = params[:user][:name]
      @current_user.introduce = params[:user][:introduction]
    end

    if @current_user.save
      flash[:notice] = "Profile was successfully updated."
      redirect_to("/users/profile")
    else
      puts @current_user.inspect
      puts @current_user.errors.full_messages
      render("users/profile")
    end
  end

  def login_form
  end

  def login
    user_params = params[:user]
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Signed in successfully."
      redirect_to("/")
    else
      @email = params[:email]
      @password = params[:password]
      flash.now[:alert] = "Invalid Email or password."
      render "login_form"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to("/")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top">
    <div class="top-main">
        <div class="container">
            <div class="row col-lg-6">
                <div class="form-fream">
                    <div class="form-area">
                        <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
                        <%= form_with url: rooms_search_path, method: :get, local: true do |f| %>
                            <%= f.label "エリア" %>
                            <%= f.text_field :search, placeholder:"東京", class:"form-control mb-4", name:"area", id:"area" %>
                            <%= f.submit "探す", name:"commit", class:"form-control btn-primary mb-4" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="panel-area m-5">
            <h1 class="section-title">おすすめのエリア</h1>
            <div class="row">
                <div class="panel-item col-lg-3 col-6">
                    <span>東京</span>
                    <%= link_to image_tag("img_tokyo.jpg", {class: "panel-image"}), "/rooms/search?area=東京" %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>大阪</span>
                    <%= link_to image_tag("img_osaka.jpg", {class: "panel-image"}), "/rooms/search?area=京都" %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>京都</span>
                    <%= link_to image_tag("img_kyoto.jpg", {class: "panel-image"}), "/rooms/search?area=沖縄" %>
                    <div class="shadow"></div>
                </div>
                <div class="panel-item col-lg-3 col-6">
                    <span>札幌</span>
                    <%= link_to image_tag("img_sapporo.jpg", {class: "panel-image"}), "/rooms/search?area=札幌" %>
                    <div class="shadow"></div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %> 
    <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoteshareApp</title>

    <script src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>

    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet"> 
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header-left-nav">
          <%= link_to image_tag("logo.png", alt: "サイトのロゴ画像"), "/" %>
          <form action="/rooms/search" accept-charset="UTF-8" method="get">
            <div class="header-search d-lg-inline-block d-none">
              <input type="text" name="area" id="area" value="" class="form-control" placeholder="エリア">
              <i class="fas fa-map-marker-alt">
              </i>
            </div>
            <div class="header-search d-lg-inline-block d-none">
              <input type="text" name="keyword" id="keyword" value="" class="form-control" placeholder="キーワード">
              <i class="fas fa-search">
              </i>
            </div>
          <input type="submit" name="commit" class="header-search d-none" value data-disable-with>
        </form>
      </div>
      <!-- ログインしてるかどうかによってどっちかを表示 -->
      <!-- ログインしてない場合 -->
      <% if @current_user %>
        <div class="header-right-nav">
          <div class="nav-item d-sm-inline-block d-none">
            <%= @current_user.name %>
          </div>
          <!-- ユーザアイコンを押下したらメニューが出るようにする -->
          <div class="nav-item">
            <img class="mx-3 p-1 host-icon nav-trigger" alt="メニュー" src="<%= @current_user.icon %>" onerror="this.onerror=null;this.src='/assets/default_icon.jpg';">
            <ul class="header-nav-menu">
              <li><a href="/rooms/new">ルーム登録</a></li>
              <li><a href="/reservations">予約済みルーム一覧</a></li>
              <li><a href="/rooms/posts">登録済みルーム一覧</a></li>
              <li><a href="/users/account">設定</a></li>
              <li><a rel="nofollow" data-method="delete" href="/logout">ログアウト</a></li>
            </ul>
          </div>
        </div>
        <!-- ログインしてる場合 -->
      <% else %>
        <div class="header-right-nav">
          <div class="nav-item">
              <%= link_to("ログイン", login_path, {class: "btn btn-primary my-2 mx-3"}) %>
              <%= link_to("登録する", signup_path, {class: "btn btn-secondary"}) %>
          </div>
        </div>
      <% end %>
    </header>
    <div class="clearfix"></div>
    <div class="notifications">  
      <% if flash[:alert] %>
        <div class="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
    <div class="main-content">
      <%= yield %>
    </div>
    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container-fiuld user"> 
    <div class="row">
        <div class="col-md-12 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="room">予約した部屋</label>
                        <div class="col-md-9"><a href="/rooms/310">a</a></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="start_date">開始日</label>
                        <div class="col-md-9">2021年05月13日</div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="end_date">終了日</label>
                        <div class="col-md-9">2021年05月28日</div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="end_date">価格</label>
                        <div class="col-md-9">15円</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
    <h4 class="pb-4">予約済みルーム一覧</h4>
    <table>
        <thead>
            <tr align="center">
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>合計料金</th>
                <th>開始日</th>
                <th>終了日</th>
                <th>予約確定日時</th>
            </tr>
        </thead>
        <tbody>
            <% @current_user.reservations.each do |reservation| %>
                <tr>
                    <td>
                        <%= link_to("/rooms/#{reservation.room_id}") do %>
                            <img src="<%= reservation.room.thumbnail %>" class="reservations-image" alt="部屋画像" onerror="this.onerror=null;this.src='/assets/room01.jpg';")
                        <% end %>
                    </td>
                    <td class="posts-name">
                        <%= link_to("#{reservation.room.name}", "/rooms/#{reservation.room.id}") %>
                    </td>
                    <td class="content">
                        <%= reservation.room.description %>
                    </td>
                    <td class="price-icon">
                        <%= reservation.total_amount %>
                    </td>
                    <td>
                        <%= reservation.start %>
                    </td>
                    <td>
                        <%= reservation.end %>
                    </td>
                    <td>
                        <%= reservation.created_at %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservations-new">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="reservations-new-nav">
                <h4 class="reservations-new-check-content">予約内容確認</h4>
                <h5 class="price-icon"><%= @room.price %> / 日</h5>
                <div class="reservations-new-date-select">
                    <form class="new_reservation" id="new_reservation" action="/reservations/create" accept-charset="UTF-8" method="post">
                        <input type="hidden" name="authenticity_token">
                        <input type="hidden" value="<%= @room.id %>" name="reservation[room_id]" id="reservation_room_id">
                        <label for="start_date">開始日</label>
                        <input class="form-control mb-4" readonly="readonly" type="text" value="<%= @reservation.start %>" name="reservation[start_date]" id="reservation_start_date">
                        <label for="end_date">終了日</label>
                        <input class="form-control mb-4" readonly="readonly" type="text" value="<%= @reservation.end %>" name="reservation[end_date]" id="reservation_end_date">
                        <h6 class="reservations-new-check-content">使用日数 : <%= @reservation_count %>日</h6>
                        <h6 class="reservations-new-check-content">人数 : <%= @reservation.person_count %>人</h6>
                        <input type="hidden" value="<%= @reservation.person_count %>" name="reservation[person_count]" id="reservation_person_count">
                        <label for="total_amount">合計金額</label>
                        <input class="form-control mb-4" readonly="readonly" type="text" value="<%= @total_price %>" name="reservation[total_amount]" id="reservation_total_amount">
                        <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
                        <input type="submit" name="commit" value="予約を確定" class="btn btn-primary form-control my-3" data-disable-with="予約を確定">
                        <a class="btn btn-secondary form-control" href="/rooms/<%= @room.id %>">ルーム詳細に戻る</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user"> 
    <div class="row">
        <div class="col-md-12 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="room">予約した部屋</label>
                        <div class="col-md-9"><a href="/rooms/310"><%= @reservation.room.name %></a></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="start_date">開始日</label>
                        <div class="col-md-9"><%= @reservation.start.strftime("%Y年%m月%d日") %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="end_date">終了日</label>
                        <div class="col-md-9"><%= @reservation.end.strftime("%Y年%m月%d日") %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="end_date">価格</label>
                        <div class="col-md-9"><%= @reservation.total_amount %>円</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fiuld room-new">
    <div class="row">
        <div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
            <ul>
                <li class="active"><a href="/rooms/new">基本情報</a></li>
            </ul>
        </div>
        <div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
            <ul>
                <li class="active"><a href="/rooms/new">基本情報</a></li>
            </ul>
        </div>
        <div class="col-lg-10 room-view">
            <div class="room-view-box">
                <%= form_tag("/rooms/create", method: :post, class: "new_room", id: "new_room", multipart: true) do %>
                    <input type="hidden" name="authenticity_token">
                    <div class="update-content">
                        <div class="row">
                            <h5>ルーム情報登録</h5>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <label class="col-md-3 required-a" for="name">ルーム名</label>
                            <input class="form-control mb-4 col-md-9" placeholder="ルーム名を入力" type="text" name="name" id="room_name">
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <label class="col-md-3 required-a" for="content">ルーム紹介</label>
                            <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="ルーム説明を入力" name="description" id="room_content"></textarea>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <label class="col-md-3 required-a" for="price">料金</label>
                            <input class="form-control mb-4 col-md-9" placeholder="一日あたりの料金を入力" type="number" name="price" id="room_price">
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <label class="col-md-3 required-a" for="address">住所</label>
                            <input class="form-control mb-4 col-md-9" placeholder="住所を入力" type="text" name="address" id="room_address">
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <label class="col-md-3 required-a" for="image">ルーム画像</label>
                            <input class="mb-4 col-md-9" placeholder="ルーム画像をアップロード" type="file" name="thumbnail" id="room_image">
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <input type="submit" name="commit" value="登録" class="col-md-2 btn btn-primary mx-3" data-disable-with="登録">
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/posts.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <%= link_to("/rooms/#{room.id}") do %>
              <img src="<%= room.thumbnail %>" class="room-posts-image" alt="部屋画像" onerror="this.onerror=null;this.src='/assets/room01.jpg';")
            <% end %>
          </td>
          <td class="posts-name">
            <%= link_to("#{room.name}", "/rooms/#{room.id}") %>
          </td>
          <td class="posts-content">
            <%= room.description %>
          </td>
          <td class="price-icon">
            <%= room.price %>
          </td>
          <td>
            <%= room.created_at %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">
    <h4 class="pb-4">検索結果：<%= @room_count %>件</h4>
    <div class="row">
        <% @rooms.each do |room| %>
            <div class="col-sm-6 col-lg-4 col-xl-3">
                <div class="room-frame-inner">
                    <%= link_to("/rooms/#{room.id}") do %>
                        <div class="room-image-out">
                            <img src="<%= room.thumbnail %>" class="room-image" alt="部屋画像" onerror="this.onerror=null;this.src='/assets/room01.jpg';">
                        </div>
                        <div class="room-profile">
                            <p class="room-profile-name"><%= room.name %></p>
                            <p class="room-profile-city"><%= room.address %></p>
                            <p class="room-profile-price price-icon"><%= room.price %></p>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
    <div class="row">
        <div class="col-md-8">
            <img onerror="this.onerror=null;this.src='/assets/room01.jpg';" alt="部屋画像" class="room-show-image"
                src="<%= @room.thumbnail %>">
            <div class="room-show-detile">
                <div class="room-show-detile-icon">
                    <a href="/">
                        <img onerror="this.onerror=null;this.src='/assets/default_icon.jpg';" alt="アイコン画像" class="host-icon" src="">
                    </a>
                </div>
                <div class="room-show-profile">
                    <p class="room-show-profile-name"><%= @room.name %></p>
                    <p class="room-show-profile-address"><%= @room.address %></p>
                </div>
            </div>
            <p class="room-show-detile-content"><%= @room.description %></p>
        </div>
        <div class="col-md-4">
            <div class="room-show-nav">
                <h5 class="price-icon"><%= @room.price %> / 日</h5>
                <div class="room-show-date-select">
                    <form action="/reservations/new" accept-charset="UTF-8" method="get">
                        <label for="start_date">開始日</label>
                        <input class="form-control mb-4" placeholder="年/月/日" type="date" name="start_date" id="start_date">
                        <label for="end_date">終了日</label>
                        <input class="form-control mb-4" placeholder="年/月/日" type="date" name="end_date" id="end_date">
                        <label for="person_count">人数</label>
                        <input class="form-control mb-4" type="number" name="person_count" id="person_count">
                        <input type="hidden" name="room_id" id="room_id" value="<%= @room.id %>">
                        <input type="submit" name="commit" value="予約する" class="btn btn-primary form-control"
                            data-disable-with="予約する">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/account.html.erb
<div class="container-fiuld user"> 
    <div class="row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
    <ul>
        <li class="active"><a href="/users/account">アカウント</a></li>
        <li class=""><a href="/users/profile">プロフィール</a></li>
    </ul>
</div>
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
    <ul>
        <li class="active"><a href="/users/account">アカウント</a></li>
        <li class=""><a href="/users/profile">プロフィール</a></li>
    </ul>
</div>
        <div class="col-md-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>アカウント</h5>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="email">メールアドレス</label>
                        <div class="col-md-9"><%= @current_user.email %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="password">パスワード</label>
                        <div class="col-md-9">*********</div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <a class="col-md-2 btn btn-primary mx-3" href="/users/edit">編集</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/login_form.html.erb
<div class="container device">
    <div class="device_frame">
        <p class="my-4">ログイン</p>
        <div class="device_inner">
            <%= form_tag("/login", method: :post, class: "new_user", id: "new_user") do %>
                <div class="field form-row">
                    <div class="col-2 required-b pt-2"></div>
                    <input autocomplete="email" class="form-control col-10 px-2" placeholder="メールアドレス" type="email" value="<%= @email %>" name="user[email]" id="user_email">
                </div>
                <div class="field form-row">
                    <div class="col-2 required-b pt-2"></div>
                    <input autocomplete="current-password" class="form-control col-10 px-2" placeholder="パスワード" type="password" name="user[password]" id="user_password">
                </div>
                <div class="actions">
                    <input type="submit" name="commit" value="ログイン" class="form-control btn-primary my-4" data-disable-with="ログイン">
                </div>
            <% end %>
            <%= link_to("新しいアカウントを作成", signup_path) %><br>
        </div>
    </div>
</div>